# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "rubocop", "~> 1.22.0"
gem "rubocop-github", "~> 0.16.2"
gem "rubocop-performance", "~>1.12.0"
gem "rubocop-rails", "~> 2.7"
gem "rubocop-rspec", "~> 2.4.0"
